# Generated by Django 3.0.5 on 2020-05-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Final_total',
            field=models.DecimalField(decimal_places=2, default=10.9, max_digits=100000),
        ),
        migrations.AddField(
            model_name='order',
            name='Sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100000),
        ),
        migrations.AddField(
            model_name='order',
            name='Tax_total',
            field=models.DecimalField(decimal_places=2, default=10.9, max_digits=100000),
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
