# Generated by Django 3.0.5 on 2020-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200510_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
