# Generated by Django 3.0.5 on 2020-05-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='orderid',
        ),
    ]
