# Generated by Django 3.0.5 on 2020-05-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_info_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
